version: 1.0.{build}
branches:
  only:
    - master

skip_tags: true
skip_branch_with_pr: true
shallow_clone: true

build:
  parallel: true
  verbosity: minimal

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PYTHON: "C:\\Python34"
      ARCH: "x86"

    - APPVEYOR_BUILD_WORKER_IMAGE: "Visual Studio 2015"
      PYTHON: "C:\\Python34-x64"
      ARCH: "x64"

install:
  - cmd: "%PYTHON%\\python.exe -m pip install --upgrade pip==19.1.1"
  - cmd: "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build_script:
  - cmd: "%PYTHON%\\python.exe -OO -m PyInstaller --onefile --noconsole --distpath build index.py"
  - cmd: 'ren "build\\index.exe" lex-win-%ARCH%.exe'

artifacts:
  - path: .\build\*
